Update

diff --git a/7a7fbb447a00edd8d010a7cd111e7ccff37b484c.patch b/7a7fbb447a00edd8d010a7cd111e7ccff37b484c.patch
--- a/7a7fbb447a00edd8d010a7cd111e7ccff37b484c.patch
+++ b/7a7fbb447a00edd8d010a7cd111e7ccff37b484c.patch
@@ -1,49 +1,47 @@
-From 7a7fbb447a00edd8d010a7cd111e7ccff37b484c Mon Sep 17 00:00:00 2001
-From: Nickolay Shmyrev <nshmyrev@gmail.com>
-Date: Sat, 4 Nov 2023 17:07:35 +0100
-Subject: [PATCH] Even less python2.7
-
----
- tools/extras/check_dependencies.sh | 29 -----------------------------
- 1 file changed, 29 deletions(-)
-
-diff --git a/tools/extras/check_dependencies.sh b/tools/extras/check_dependencies.sh
-index 2591c4b6bae..0b91d79be00 100755
---- a/tools/extras/check_dependencies.sh
-+++ b/tools/extras/check_dependencies.sh
-@@ -93,35 +93,6 @@ if ! have python3; then
-   pythonok=false
+diff -up kaldi-master/tools/extras/check_dependencies.sh.3~ kaldi-master/tools/extras/check_dependencies.sh
+--- kaldi-master/tools/extras/check_dependencies.sh.3~	2025-09-22 09:05:59.000000000 +0200
++++ kaldi-master/tools/extras/check_dependencies.sh	2025-11-17 17:15:03.746043053 +0100
+@@ -109,43 +109,6 @@ else
+   pythonok=true
  fi
  
 -(
 -#Use a subshell so that sourcing env.sh does not have an influence on the rest of the script
 -[ -f ./env.sh ] && . ./env.sh
--if $pythonok && ! have python2; then
--  mkdir -p $PWD/python
--  echo "$0: python2.7 is installed, but the python2 binary does not exist." \
--       "Creating a symlink and adding this to tools/env.sh"
--  ln -s $(command -v python2.7) $PWD/python/python2
--  echo "export PATH=$PWD/python:\${PATH}" >> env.sh
--fi
--
--if [[ -f $PWD/python/.use_default_python && -f $PWD/python/python ]]; then
--  rm $PWD/python/python
--fi
--
--if $pythonok && have python && [[ ! -f $PWD/python/.use_default_python ]]; then
--  version=$(python 2>&1 --version | awk '{print $2}')
--  if [[ $version != "2.7"* ]] ; then
--    echo "$0: WARNING python 2.7 is not the default python. We fixed this by" \
--         "adding a correct symlink more prominently on the path."
--    echo " ... If you really want to use python $version as default, add an" \
+-rm -f $PWD/python/python*
+-if ! [ -f $PWD/python/.use_default_python ]; then
+-  echo "$0: Configuring python"
+-  echo "$0: ... If you really want to avoid this, add an" \
 -         "empty file $PWD/python/.use_default_python and run this script again."
--    mkdir -p $PWD/python
+-  if $python27 ; then
+-    echo "$0: ... python2.7 found, making it default (python, python2, python2.7)"
 -    ln -s $(command -v python2.7) $PWD/python/python
--    echo "export PATH=$PWD/python:\${PATH}" >> env.sh
+-    ln -s $(command -v python2.7) $PWD/python/python2
+-    ln -s $(command -v python2.7) $PWD/python/python2.7
+-  fi
+-
+-  if $python3 ; then
+-    echo "$0: ... python3 found, making symlink (python3)"
+-    ln -s $(command -v python3) $PWD/python/python3
+-    if ! $python27 ; then
+-      echo "$0: ... ... python2.7 not found, using python3 as python"
+-      ln -s $(command -v python3) $PWD/python/python
+-    fi
+-  fi
+-else
+-  echo "$0: Not configuring python(s) -- using system defaults"
+-  if ! have python ; then
+-    echo "$0: WARNING: 'python' executable not present, configuring"
+-    if $python27 ; then
+-      ln -s $(command -v python2.7) $PWD/python/python
+-    elif $python3 ; then
+-      ln -s $(command -v python3) $PWD/python/python
+-    fi
 -  fi
 -fi
+-
 -)
 -
  mathlib_missing=false
- case $(uname -m) in
-   x86_64)  # Suggest MKL on an Intel64 system (not supported on i?86 hosts).
+ case "$(uname -m)-$(uname -s)" in
+   x86_64*)  # Suggest MKL on an Intel64 system (not supported on i?86 hosts).
